# Full reference https://github.com/foundry-rs/foundry/tree/master/crates/config

[profile.default]
  auto_detect_solc = false
  block_timestamp = 1_738_368_000 # Feb 1, 2025 at 00:00 GMT
  bytecode_hash = "none"
  evm_version = "prague"
  fuzz = { runs = 1_000 }
  gas_reports = ["*"]
  optimizer = true
  optimizer_runs = 10_000
  out = "out"
  script = "script"
  solc = "0.8.30"
  src = "src"
  test = "tests"
  fs_permissions = [{ access = "read", path = "./"}]
  ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
via-ir = true

[profile.ci]
  fuzz = { runs = 10_000 }
  verbosity = 4

[etherscan]
  base = { key = "${SCAN_API_KEY}" }
  base_sepolia = { key = "${SCAN_API_KEY}" }

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true

[rpc_endpoints]
  base = { endpoint = "${RPC_URL}" }
  base_sepolia = { endpoint = "${RPC_URL}" }
