name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test & Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run type checking
        run: bun run tsc --noEmit

      - name: Run linting and formatting
        run: |
          bunx biome ci .

      - name: Run tests
        run: bun test

  security:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-ref: "."
          format: "sarif"
          output: "trivy-results.sarif"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: "trivy-results.sarif"
          category: "trivy-filesystem"

      - name: Run CodeQL Analysis
        uses: github/codeql-action/init@v3
        with:
          languages: typescript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  docker:
    name: Docker Build Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build TEE Docker image (test)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: false
          load: true
          tags: tee-ts:test
          cache-from: type=gha,scope=tee-ci
          cache-to: type=gha,mode=max,scope=tee-ci

      - name: Build Nginx Docker image (test)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./nginx.Dockerfile
          platforms: linux/amd64
          push: false
          load: true
          tags: tee-ts-nginx:test
          cache-from: type=gha,scope=nginx-ci
          cache-to: type=gha,mode=max,scope=nginx-ci

      - name: Run Trivy vulnerability scanner on TEE image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "tee-ts:test"
          format: "sarif"
          output: "trivy-tee-image.sarif"

      - name: Run Trivy vulnerability scanner on Nginx image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "tee-ts-nginx:test"
          format: "sarif"
          output: "trivy-nginx-image.sarif"

      - name: Upload Trivy TEE image scan results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: "trivy-tee-image.sarif"
          category: "trivy-tee-image"

      - name: Upload Trivy Nginx image scan results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: "trivy-nginx-image.sarif"
          category: "trivy-nginx-image"
